### ISSUE TITLE
Parsing JSON

### ISSUE THREAD

**Issue by rramirez-dev** [raywenderlich/ios-interview#4]
I'm having difficulty getting the JSON data to map to my  codeable structs. In this project should I be doing the json parsing myself or use a third party library? Is the goal of this project to demonstrate how I can handle translating json data? I feel like I should not be spending all my time parsing the json data and handling special characters. Is there something I'm missing?

**Comment by Zoha131** [comment]
Can you describe your difficulty? An example would help to understand your problem.

**Comment by rramirez-dev** [comment]
Did you use a third party library to parse the JSON? I'm getting the following error: The data couldn’t be read because it isn’t in the correct format. There are so many nested objects that need to be created use codeable.

**Comment by shruti1512** [comment]
Hey @rramirez-dev  You are getting this error because your decodable data structure for the parsed json response isn't correct. Yeah you are right the structure does require multiple nested objects to fetch the attributes that need to be displayed in the app.  Try to analyze the data from the root to the property that you need step-by-step like what is an array here which one is dictionary, what is they key of the dictionary and then eventually you will get the entire data structure. I would suggest not to use any third party library for this because JSON Parsing is an important requirement that is asked in take home practice tests. Practicing it here would help you prepare better for future tests.

**Comment by rramirez-dev** [comment]
After reviewing the NetworkManager implementations in the PR's I was able to get results from the api. I though that I had to implement structs for all the objects in the json file, I did not have to do that, I just created a Results Obj for the root node, and then Attribute and Item for the nested nodes.
